/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CareerPathService } from "../careerPath.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CareerPathCreateInput } from "./CareerPathCreateInput";
import { CareerPath } from "./CareerPath";
import { CareerPathFindManyArgs } from "./CareerPathFindManyArgs";
import { CareerPathWhereUniqueInput } from "./CareerPathWhereUniqueInput";
import { CareerPathUpdateInput } from "./CareerPathUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CareerPathControllerBase {
  constructor(
    protected readonly service: CareerPathService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CareerPath })
  @nestAccessControl.UseRoles({
    resource: "CareerPath",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCareerPath(
    @common.Body() data: CareerPathCreateInput
  ): Promise<CareerPath> {
    return await this.service.createCareerPath({
      data: data,
      select: {
        careerDescription: true,
        careerName: true,
        createdAt: true,
        id: true,
        stepsToAchieve: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CareerPath] })
  @ApiNestedQuery(CareerPathFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CareerPath",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async careerPaths(@common.Req() request: Request): Promise<CareerPath[]> {
    const args = plainToClass(CareerPathFindManyArgs, request.query);
    return this.service.careerPaths({
      ...args,
      select: {
        careerDescription: true,
        careerName: true,
        createdAt: true,
        id: true,
        stepsToAchieve: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CareerPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CareerPath",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async careerPath(
    @common.Param() params: CareerPathWhereUniqueInput
  ): Promise<CareerPath | null> {
    const result = await this.service.careerPath({
      where: params,
      select: {
        careerDescription: true,
        careerName: true,
        createdAt: true,
        id: true,
        stepsToAchieve: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CareerPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CareerPath",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCareerPath(
    @common.Param() params: CareerPathWhereUniqueInput,
    @common.Body() data: CareerPathUpdateInput
  ): Promise<CareerPath | null> {
    try {
      return await this.service.updateCareerPath({
        where: params,
        data: data,
        select: {
          careerDescription: true,
          careerName: true,
          createdAt: true,
          id: true,
          stepsToAchieve: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CareerPath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CareerPath",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCareerPath(
    @common.Param() params: CareerPathWhereUniqueInput
  ): Promise<CareerPath | null> {
    try {
      return await this.service.deleteCareerPath({
        where: params,
        select: {
          careerDescription: true,
          careerName: true,
          createdAt: true,
          id: true,
          stepsToAchieve: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
