/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AptitudeTestService } from "../aptitudeTest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AptitudeTestCreateInput } from "./AptitudeTestCreateInput";
import { AptitudeTest } from "./AptitudeTest";
import { AptitudeTestFindManyArgs } from "./AptitudeTestFindManyArgs";
import { AptitudeTestWhereUniqueInput } from "./AptitudeTestWhereUniqueInput";
import { AptitudeTestUpdateInput } from "./AptitudeTestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AptitudeTestControllerBase {
  constructor(
    protected readonly service: AptitudeTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AptitudeTest })
  @nestAccessControl.UseRoles({
    resource: "AptitudeTest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAptitudeTest(
    @common.Body() data: AptitudeTestCreateInput
  ): Promise<AptitudeTest> {
    return await this.service.createAptitudeTest({
      data: data,
      select: {
        createdAt: true,
        id: true,
        testDescription: true,
        testName: true,
        testQuestions: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AptitudeTest] })
  @ApiNestedQuery(AptitudeTestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AptitudeTest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aptitudeTests(@common.Req() request: Request): Promise<AptitudeTest[]> {
    const args = plainToClass(AptitudeTestFindManyArgs, request.query);
    return this.service.aptitudeTests({
      ...args,
      select: {
        createdAt: true,
        id: true,
        testDescription: true,
        testName: true,
        testQuestions: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AptitudeTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AptitudeTest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aptitudeTest(
    @common.Param() params: AptitudeTestWhereUniqueInput
  ): Promise<AptitudeTest | null> {
    const result = await this.service.aptitudeTest({
      where: params,
      select: {
        createdAt: true,
        id: true,
        testDescription: true,
        testName: true,
        testQuestions: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AptitudeTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AptitudeTest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAptitudeTest(
    @common.Param() params: AptitudeTestWhereUniqueInput,
    @common.Body() data: AptitudeTestUpdateInput
  ): Promise<AptitudeTest | null> {
    try {
      return await this.service.updateAptitudeTest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          testDescription: true,
          testName: true,
          testQuestions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AptitudeTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AptitudeTest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAptitudeTest(
    @common.Param() params: AptitudeTestWhereUniqueInput
  ): Promise<AptitudeTest | null> {
    try {
      return await this.service.deleteAptitudeTest({
        where: params,
        select: {
          createdAt: true,
          id: true,
          testDescription: true,
          testName: true,
          testQuestions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
